### ISSUE TITLE
🐛

### ISSUE THREAD

**Issue by Clavien317** [KinsonDigital/CSharpLibTemplateRepo#2]
### I have done the items below . . .

- [X] I have updated the title without removing the 🐛 emoji.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

- [ ] Windows
- [X] Linux
- [ ] Android
- [ ] Mac OS
- [ ] iOS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CalvinWilkinson** [comment]
@Clavien317 Hello Clavien!!  I noticed that 2 hours ago you created 2 separate issues.  I noticed that the issues are empty.  Just curious what you are trying to do.

Are you wanting to create an issue to try and fix something? 

Cheers!!

**Comment by CalvinWilkinson** [comment]
Reason: No response from @Clavien317

**Comment by Clavien317** [comment]
HELLO

**Comment by CalvinWilkinson** [comment]
@Clavien317 Are you interested in contributing to some of my projects?

If so, we can talk a bit and maybe get you started.  
If you are interested, you can joint my discord channel and we can chat.

Go to this discord link [here](https://discord.gg/qewu6fNgv7) to join.

If you do not know what Discord is, it is a messaging application for gamers, developers, or for whatever you want it to be.  It is completely free and downloaded [here](https://discord.com/download).
